apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: im9qi0v5t-go
  janus-idp.io/tekton: im9qi0v5t-go
  backstage.io/kubernetes-id: im9qi0v5t-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: im9qi0v5t-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
