apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: im9qi0v5t-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: im9qi0v5t-go 
  name: im9qi0v5t-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: im9qi0v5t-go 
